pull_request_rules:
  - name: merge documentation into dev
    conditions:
      - status-success=Travis CI - Pull Request
      - status-success=coverage/coveralls
      - base=dev
      - head=documentation
    actions:
      merge:
        method: rebase
  - name: add tags to documenation
    conditions:
      - base=dev
      - head=documentation
    actions:
      label:
        add:
        - enhancement