on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1 
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install GREN
        uses: actions/npm@master
        with:
          args: npm install github-release-notes -g
      - name: Run Gren
        run: |
          gren release